# Generated by Django 4.1.3 on 2023-01-03 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetailsstudentmainmarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('Grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('Sem', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII')])),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetailsstudentmainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(choices=[('IT', 'IT'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=30)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('Marks', models.ManyToManyField(to='studentdetails.studentdetailsstudentmainmarksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='studentdetailsStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='studentdetailsStudentdetailsModel',
        ),
        migrations.AddField(
            model_name='studentdetailsstudentmainmodel',
            name='Owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentdetails.studentdetailsstudentmodel'),
        ),
        migrations.AddField(
            model_name='studentdetailsstudentmainmarksmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentdetails.studentdetailsstudentmodel'),
        ),
    ]
