# Generated by Django 4.1.3 on 2023-01-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0003_remove_studentdetailsstudentmainmarksmodel_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailsstudentmainmarksmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentdetailsstudentmainmarksModel_owner', to='studentdetails.studentdetailsstudentmodel'),
        ),
        migrations.AlterField(
            model_name='studentdetailsstudentmainmodel',
            name='Owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentdetailsstudentmainModel_owner', to='studentdetails.studentdetailsstudentmodel'),
        ),
    ]
