# Generated by Django 4.1.3 on 2023-01-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0004_alter_studentdetailsstudentmainmarksmodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailsstudentmainmarksmodel',
            options={'verbose_name': 'Student Mark Model'},
        ),
        migrations.AlterModelOptions(
            name='studentdetailsstudentmainmodel',
            options={'verbose_name': 'Student Main Model'},
        ),
        migrations.AlterModelOptions(
            name='studentdetailsstudentmodel',
            options={'verbose_name': 'Student Model'},
        ),
        migrations.AlterField(
            model_name='studentdetailsstudentmodel',
            name='Image',
            field=models.ImageField(blank=True, upload_to='student/image'),
        ),
    ]
