# Generated by Django 4.1.3 on 2023-01-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0005_alter_studentdetailsstudentmainmarksmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetailsstudentmainmarksmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentdetailsstudentmainmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentdetailsstudentmodel',
            options={},
        ),
    ]
