# Generated by Django 4.1.3 on 2023-01-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsuserloginotpmodel',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserLoginOTPModel_Owner', to='accounts.accountsuser'),
        ),
        migrations.AlterField(
            model_name='accountsuserprofile',
            name='Owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserProfile_Owner', to='accounts.accountsuser'),
        ),
    ]
