# Generated by Django 4.1.3 on 2023-01-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountsuserloginotpmodel_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_Customer', models.BooleanField(default=False)),
                ('is_Admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='accountsUserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountsuserloginotpmodel',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='accountsuserprofile',
            name='Owner',
        ),
    ]
