# Generated by Django 4.1.3 on 2023-01-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_accountsuser_delete_accountsuserloginotpmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsUserLoginOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('active', models.BooleanField()),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserLoginOTPModel_Owner', to='accounts.accountsusermodel')),
            ],
        ),
    ]
