# Generated by Django 4.1.3 on 2023-01-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productsusercartmodel_owner'),
        ('accounts', '0008_rename_phonenumber_accountsusermodel_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsUserCartProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserCartProductsModel_owner', to='accounts.accountsusermodel')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserCartProductsModel_product', to='products.productspmodel')),
            ],
        ),
        migrations.CreateModel(
            name='accountsUserCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalprice', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='accountsUserCartModel_owner', to='accounts.accountsusermodel')),
                ('products', models.ManyToManyField(to='accounts.accountsusercartproductsmodel')),
            ],
        ),
    ]
