# Generated by Django 4.1.3 on 2023-01-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinalPrice', models.IntegerField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsuser')),
                ('Products', models.ManyToManyField(to='products.accountsusercartproductsmodel')),
            ],
        ),
    ]
