# Generated by Django 4.1.3 on 2023-01-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderMainModel',
        ),
    ]
