# Generated by Django 4.1.3 on 2023-01-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountsUserCartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsuser')),
            ],
        ),
        migrations.CreateModel(
            name='productsPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('UniqueCode', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='productsPImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, upload_to='')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspmodel')),
            ],
        ),
        migrations.CreateModel(
            name='productsOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FinalPrice', models.IntegerField()),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsuser')),
                ('Products', models.ManyToManyField(to='products.accountsusercartproducts')),
            ],
        ),
        migrations.CreateModel(
            name='accountsUserCartProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsuser')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspmodel')),
            ],
        ),
        migrations.AddField(
            model_name='accountsusercartproducts',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspmodel'),
        ),
        migrations.CreateModel(
            name='accountsUserCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountsuser')),
                ('Products', models.ManyToManyField(to='products.productspmodel')),
            ],
        ),
    ]
