# Generated by Django 4.1.3 on 2023-01-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspmodel',
            name='UniqueCode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
