# Generated by Django 4.1.3 on 2023-01-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountsusermodel_accountsuserprofilemodel_and_more'),
        ('order', '0002_delete_ordermainmodel'),
        ('products', '0002_alter_productspmodel_uniquecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsUserCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsUserCart_Owner', to='accounts.accountsusermodel')),
            ],
        ),
        migrations.CreateModel(
            name='productsUserCartPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsUserCartP_Owner', to='accounts.accountsusermodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountsusercartproducts',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='accountsusercartproducts',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='accountsusercartproductsmodel',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='accountsusercartproductsmodel',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='productsordermodel',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='productsordermodel',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='productspimagemodel',
            name='Product',
        ),
        migrations.RenameField(
            model_name='productspmodel',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productspmodel',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='productspmodel',
            old_name='UniqueCode',
            new_name='uniqueCode',
        ),
        migrations.AddField(
            model_name='productspmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='accountsUserCartModel',
        ),
        migrations.DeleteModel(
            name='accountsUserCartProducts',
        ),
        migrations.DeleteModel(
            name='accountsUserCartProductsModel',
        ),
        migrations.DeleteModel(
            name='productsOrderModel',
        ),
        migrations.DeleteModel(
            name='productsPImageModel',
        ),
        migrations.AddField(
            model_name='productsusercartpmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsUserCartP_Product', to='products.productspmodel'),
        ),
        migrations.AddField(
            model_name='productsusercartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsUserCart_Product', to='products.productspmodel'),
        ),
    ]
