# Generated by Django 4.1.3 on 2023-01-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsusercartmodel_productsusercartpmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productsPImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsPImage_Product', to='products.productspmodel')),
            ],
        ),
    ]
