# Generated by Django 4.1.3 on 2023-01-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productspimagemodel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsusercartmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsusercartmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='productsusercartmodel',
            name='finalPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsusercartmodel',
            name='products',
            field=models.ManyToManyField(related_name='productsUserCart_product', to='products.productspmodel'),
        ),
    ]
