# Generated by Django 4.1.3 on 2023-01-10 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountsuserloginotpmodel_owner_and_more'),
        ('products', '0006_remove_productsusercartmodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsusercartmodel',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productsUserCart_owner', to='accounts.accountsusermodel'),
        ),
    ]
