# Generated by Django 4.1.3 on 2023-01-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermainmodel_products'),
        ('products', '0007_alter_productsusercartmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsusercartpmodel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='productsusercartpmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='productsUserCartModel',
        ),
        migrations.DeleteModel(
            name='productsUserCartPModel',
        ),
    ]
